---
apiVersion: v1
kind: ServiceAccount
metadata:
  labels:
    app: redis-pod-labeler
  name: redis-pod-labeler-service-account
  namespace: staging
---
kind: ClusterRole
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: redis-pod-labeler-role
  namespace: staging
rules:
  - apiGroups: [""]
    resources: ["namespaces", "pods"]
    verbs: ["get", "patch", "list"]
  - apiGroups: [""]
    resources: ["services"]
    verbs: ["get", "list"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: redis-pod-labeler-rolebinding
  namespace: staging
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: redis-pod-labeler-role
subjects:
  - kind: ServiceAccount
    name: redis-pod-labeler-service-account
    namespace: staging
---
kind: Deployment
apiVersion: apps/v1
metadata:
  labels:
    app: redis-pod-labeler
  name: redis-pod-labeler
  namespace: staging
spec:
  replicas: 1
  revisionHistoryLimit: 5
  selector:
    matchLabels:
      app: redis-pod-labeler
  template:
    metadata:
      labels:
        app: redis-pod-labeler
    spec:
      containers:
        - name: redis-pod-labeler
          imagePullPolicy: Always
          image: "mithucste30/redis-pod-labeler:1.0.8"
          args:
            - ./redis-labeler.py
            - --namespace=staging    # namespace which deployed redis
            - --update-period=60   # how frequent labelling should happen( default to 60 seconds = 1 minute )
            - --redis-cluster-name=staging-cache-master # redis cluster name
            - --redis-headless-svc-name=staging-cache-headless # redis headless service name
            - --company-domain=ltn-cache-staging
            - --verbose
          livenessProbe:
            exec:
              command:
                - /bin/sh
                - -c
                - ps uaxw | egrep 'python' | grep -v 'grep'
          readinessProbe:
            exec:
              command:
                - /bin/sh
                - -c
                - ps uaxw | egrep 'python' | grep -v 'grep'
          resources:
            limits:
              cpu: 300m
              memory: 300Mi
            requests:
              cpu: 100m
              memory: 100Mi
      serviceAccountName: redis-pod-labeler-service-account